### ISSUE TITLE
No such file or directory: **/classification.csv

### ISSUE THREAD

**Issue by narakai** [NoelDeMartin/Japanese-Character-Recognition#1]
seems **/classification.csv is missing from project

**Comment by NoelDeMartin** [comment]
It's missing because it isn't source code. That file is generated after running the script `data/prepare.py`. I didn't include this file (nor many others, like the trained models) because they are generated at runtime and shouldn't be tracked with version control.

You can read the instructions in the readme on how to generate the files and train the model. Let me know if you have any problems that I can help you with :).

**Comment by narakai** [comment]
Thanks for the advice. I tried run data/prepare.py but classification.csv is still not generated.(only categories.csv and data), did I miss anything else?

**Comment by narakai** [comment]
seems something wrong with the ETL1.ZIP, got error message below:

Extracting raw/ETL1.zip...
raw/ETL1.zip extracted!
Unpacking katakana...
Traceback (most recent call last):
  File "data/prepare.py", line 120, in <module>
    main()
  File "data/prepare.py", line 20, in main
    unpack_katakana()
  File "data/prepare.py", line 84, in unpack_katakana
    prepare_image(data_file, file.read(2016))
  File "data/prepare.py", line 106, in prepare_image
    image = ImageEnhance.Brightness(image).enhance(40)
  File "/Users/laileon/Documents/virtualenv/ENV/lib/python2.7/site-packages/PIL/ImageEnhance.py", line 37, in enhance
    return Image.blend(self.degenerate, self.image, factor)
  File "/Users/leon/Documents/virtualenv/ENV/lib/python2.7/site-packages/PIL/Image.py", line 2698, in blend
    return im1._new(core.blend(im1.im, im2.im, alpha))
ValueError: image has wrong mode

**Comment by narakai** [comment]
I commented 'image = ImageEnhance.Brightness(image).enhance(40)' and it works now.

**Comment by NoelDeMartin** [comment]
I've tried it and you're right, so I'll reopen the issue until I fix this. Either removing that line or fixing it. The thing is that enhancing the brightness was important to improve the data quality when classifying, with the images as they are it doesn't give good results.
